create table BANK
(
    ID   bigint generated by default as identity
        (start with 1, increment by 1) not null primary key,
    NAME varchar(32)                   not null,
);

create table CLIENT
(
    ID           bigint generated by default as identity
        (start with 1, increment by 1) not null primary key,
    FIO          varchar(32)           not null,
    BANK_ID      bigint                not null,
    PHONE_NUMBER varchar(32)           not null,
    EMAIL        varchar(32)           not null,
    PASSPORT     varchar(32)           not null,
    constraint FK_CLIENT_BANK foreign key (BANK_ID) references BANK (ID) on delete restrict,
);

create table CREDIT
(
    ID            bigint generated by default as identity
        (start with 1, increment by 1) not null primary key,
    BANK_ID       bigint               not null,
    LIMIT         float                not null,
    INTEREST_RATE float                not null,
        constraint FK_CREDIT_BANK foreign key (BANK_ID) references BANK (ID) on delete restrict
);

create table OFFER
(
    ID               bigint generated by default as identity
        (start with 1, increment by 1) not null primary key,
    CLIENT_ID        bigint            not null,
    CREDIT_ID        bigint            not null,
    CREDIT_AMOUNT    float             not null,
    constraint FK_OFFER_CREDIT foreign key (CREDIT_ID) references CREDIT (ID) on delete restrict,
    constraint FK_OFFER_CLIENT foreign key (CLIENT_ID) references CLIENT (ID) on delete restrict,
);

create table SCHEDULE
(
    ID                     bigint generated by default as identity
        (start with 1, increment by 1) not null primary key,
    OFFER_ID              bigint      not null,
    DATE_PAYMENT           date        not null,
    AMOUNT_PAYMENT         float       not null,
    AMOUNT_PAYMENT_BODY    float       not null,
    AMOUNT_PAYMENT_PERCENT float       not null
        constraint FK_SCHEDULE_CLIENT foreign key (OFFER_ID) references OFFER (ID) on delete restrict,
);
